"""empty message

Revision ID: ba7ab02698ac
Revises: fc68d824fe58
Create Date: 2021-11-04 11:14:47.902853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7ab02698ac'
down_revision = 'fc68d824fe58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'salary_range',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'salary_range',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
